from ._version import __version__
from .auth import Credentials, SessionInfo
from .client import OXMailClient
from .config import ClientConfig, RetryConfig, TimeoutConfig
from .exceptions import (
    APIError,
    AuthenticationError,
    ClientClosedError,
    ConfigurationError,
    HTTPError,
    IMAPError,
    InvalidResponseError,
    NotAuthenticatedError,
    OXMailError,
    TransportError,
)
from .imap import IMAPConfig
from .mail import (
    Attachment,
    BackgroundWatcher,
    Checkpoint,
    CheckpointStore,
    FailoverMailSource,
    FolderState,
    HTTPMailSource,
    IMAPMailSource,
    InboxWatcher,
    JSONFileCheckpointStore,
    MailAddress,
    MailMessage,
    MailPage,
    MailSource,
    MemoryCheckpointStore,
    OutgoingMessage,
    SendResult,
)

__all__ = [
    "APIError",
    "Attachment",
    "AuthenticationError",
    "BackgroundWatcher",
    "Checkpoint",
    "CheckpointStore",
    "ClientClosedError",
    "ClientConfig",
    "ConfigurationError",
    "Credentials",
    "FolderState",
    "HTTPError",
    "InboxWatcher",
    "InvalidResponseError",
    "JSONFileCheckpointStore",
    "FailoverMailSource",
    "HTTPMailSource",
    "IMAPConfig",
    "IMAPError",
    "IMAPMailSource",
    "MailSource",
    "MailAddress",
    "MailMessage",
    "MailPage",
    "MemoryCheckpointStore",
    "NotAuthenticatedError",
    "OutgoingMessage",
    "OXMailClient",
    "OXMailError",
    "RetryConfig",
    "SendResult",
    "SessionInfo",
    "TimeoutConfig",
    "TransportError",
    "__version__",
]
